//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace BRIOPRASample {
    
    
<<<<<<< HEAD
    public partial class LiniBisnis {
=======
    public partial class ManajemenInsiden{
>>>>>>> 9a2b1edef51768bdf735a23299d6d7452f5f532c
    }
}
